---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitHubClaim
metadata:
  name: x1
spec:
  id: x1
  parameters:
    public: true
    registry: ttl.sh
    app:
      language: go
      host: my-repo.acme.com
      namespace: a-team
    db:
      enabled: true
      provider: aws
      version: "16.2"
    repo:
      user: vfarcic
    gitops:
      enabled: 
      user: 
      repo: 